version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "5000:5000" # port container: port local
    volumes:
      - type: bind
        source: ./backend
        target: /app
      - type: volume
        source: go-modules
        target: /go/pkg/mod
    command: air -c .air.toml
    environment:
      - CGO_ENABLED=0
      - DB_USER=${DB_USER}
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
  go-modules:
